Makefile
README.md
auth-plug.c
be-mongo.c
be-mongo.h
config.mk.in

Basically same as https://github.com/jpmens/mosquitto-auth-plug/pull/22 - except, removed the objectionable parts and updated the prototypes to match the latest.
Auth method is implemented and ACL hard-coded to return 1. Framework for ACL is present for any MongoDB expert to just fill-in.

MongoDB skeleton

---

be-http.c

My previous attempt was bad since a malformed request could stop the process.
That should do the job ;)

calculate escaped string length instead of throwing a fatal error

---

Makefile
auth-plug.c
be-http.c
be-http.h
envs.c
envs.h

In this p-r, env vars could be used as http request parameters.
Add config lines into the mosquitto.conf
```auth_opt_<interface>_<method>_params <key>=<evn_name>[,<key>=<evn_name>]* ```
eg for the Http interface :
1) Set these env vars like this
```
export DOMAIN=example.com
export PORT=8080
```
2) Add this configs in the mosquitto.conf
```
auth_opt_http_getuser_params domain=DOMAIN,port=PORT
auth_opt_http_superuser_params domain= DOMAIN,port=PORT
auth_opt_http_aclcheck_params domain= DOMAIN,port=PORT
```
3) The Http parameters will like
```
|-- url=http://127.0.0.1:8080/auth/
|-- data=domain=example.com&port=8080&username=xxx&password=ax&topic=&acc=-1&clientid=
```
```
|-- url=http://127.0.0.1:8080/superuser/
|-- data=domain=example.com&port=8080&username=xxx&password=&topic=&acc=-1&clien …
```

env vars could be used as http request parameters

---

be-http.c
be-http.h

In this p-r, https could be used instead of http .
Add config lines into the mosquitto.conf, the defauls value is FALSE.
``` auth_opt_http_with_ssl true ```
eg for the Http interface :
1) Add this cnfigs in the mosquitto.conf
```
auth_opt_http_with_ssl true
```
2) The Https request will like
```
|-- url=https://example.com:443/auth/
|-- data=domain=example.com&port=8080&username=xxx&password=ax&topic=&acc=-1&clientid=
```
```
|-- url=https://example.com:443/superuser/
|-- data=domain=example.com&port=8080&username=xxx&password=&topic=&acc=-1&clientid=
```
```
|-- url=https://example.com:443/acl/
|-- data=domain=example.com&port=8080&username=xxx&password=&topic=abc&acc=2&clientid=mosqpub/6349-mqttkaf001
```
We will be happy if you can accept our's code :)

Https could be used instead of http

---

be-http.c

This is an attempt to address issue #87. It sends the username/password in the body as well as using the Basic Auth header.
Here are the related curl options: http://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html

Send username and password in basic auth header for http be

---

cache.c

If I correctly understood how caching work, I've found two small bugs:
Memory leak:
HASH_DELETE do not free the aclcache structure, so I've added a call to free() after each HASH_DELETE call.
Expired entry returned:
In cache_q, when an entry is found in hash table, we check if it's expired. If so, we remove it from hash table but also return the expired result. I've modified to only return cached result if not expired.
Does it look correct for you ?

Fix memory leak in caching and don't return expired entry

---

be-http.c

curl_slist_append returns the new start of the list, which needs to be
stored. Without this, the list elements are lost right away, and the
memory of both the linked list items and strings (as they are copied)
is leaked.

Fix memory leak when building the list of headers

---

README.md

Documentation didn't tell us that clientid was passed to aclcheck (for be-http).
Add "clientid" parameter to URI-Param table

[DOC] Added "clientid" to list of URI-param for be-http

---

auth-plug.c
cache.c

Their is two way debug logs are called:
```_log(DEBUG, ...)``` and ```_log(LOG_DEBUG, ...)```
This pull request unify all call, using ```_log(LOG_DEBUG, ...)```

Inconsistent use of DEBUG/LOG_DEBUG

---

README.md
auth-plug.c
backends.h
be-http.c
be-mysql.c
be-postgres.c
be-redis.c
cache.c

This pull request return MOSQ_ERR_UNKNOWN in ACL check when backend are unreachable or broken.
The issue solved is that when your HTTP (or MySQL) backend is down, the current code return MOSQ_DENY_ACL. Which means that : 1) the message is rejected without notification for the sender 2) that rejection is cached for 5 minutes
By returning MOSQ_ERR_UNKNOWN in such case : 
1) the sender is "notified" (it is disconnected)
2) the rejection is not cached.
The new code only return MOSQ_ERR_UNKNOWN if at least one backend was unreachable and no other backend authorized the access.
I've updated backend to return such error when the backend fail due to network error / service down or
due to internal error of that backend. This means for HTTP : 5xx are considered as error and not longer as deny_acl. …

Handle backend downtime in a safer way

---

be-mongo.c

Added support for MongoDB user authentication by reading mongo_user, mongo_password and mongo_authSource from the configuration and building the uri. The added fields are optional.
For example, using these settings in `mosquitto.conf`:
```
auth_opt_backends mongo
auth_opt_mongo_user mosquitto
auth_opt_mongo_password secret
auth_opt_mongo_authSource users
```
Builds the uri `mongodb://mosquitto:secret@localhost:27017?authSource=users`.

Support for MongoDB user authentication

---

README.md
be-http.c
be-http.h

As there is not authentication for superuser and acl, we have implemented a new feature.
Here we will accept a new configuration to get the basic auth key from mosquitto.conf and if present we will set as authorization header in all post request.
Kindly please review it and merge to master.

Added basic authentication for http

---

README.md
be-http.c
be-http.h

This PR add a retry for HTTP backend if backend return an error (5xx or don't respond at all).
This is useful if there are multiple backends behind a load-balancer and some backend are unhealthy.
The retry count is configurable with a default to 3.

Added retry to HTTP backend

---

be-http.c
be-http.h

This changes allows the use of the http_hostname parameter to resolve the server ip rather than strictly requiring a hard-coded ip address in the mosquitto.conf file.

Allow connection using hostname instead of ip

---

cache.c

> EVP_MD_CTX_new() and EVP_MD_CTX_free() in OpenSSL 1.1.
This patch permits compilation on RHEL7 systems (that have
OpenSSL tagged as 1.0)

Add OpenSSL version conditional around use of EVP_MD_CTX_new/_free

---

Makefile
be-mongo.c

- at least for `mongo-c-driver` version >= 1.3.1
- as it is explained here: [https://jira.mongodb.org/browse/CDRIVER-708](https://jira.mongodb.org/browse/CDRIVER-708)
Solved removing the loops through the recordsets (since each query is expected to return 0 or 1 records) and getting rid of the check `mongoc_cursor_more`.
Solved adding a `-Wno-deprecated-declarations` flag if building for mongo backend, to preserve compatibility with previous `mongo-c-driver`.

mongo backend fixes

---

README.md
be-mongo.c

A few minor improvements to the mongo backend mostly around resilience.
* Don't segfault on improperly formatted documents (missing `user.[location_superuser]` property, missing `user.[location_topicId]` property, missing `topic.topics` list in topics document.
* Allow `user.[location_topicId]` to be an int, a string, or a ObjectID. This fixes a breaking change introduced by https://github.com/jpmens/mosquitto-auth-plug/commit/fff09583f0215c442baad2ea54f5e8d13c5be8a8 where `user.[location_topicId]` switched from needing to be an int to needing to be an ObjectID.
* Allow `user.[location_superuser]` to be unset, in which case it is treated as false. If set, allow any type which can be case to a boolean.

[mongo] Don't segfault on missing fields, allow oid|utf8|int for topics pointer

---

README.md
be-mongo.c

This adds an additional feature - support a topic array embedded within the user document. This is obviously faster and easier on the database, and fits better with the denormalised philosophy of a document store, especially where each user has a different ACL (eg, topics containing usernames).
(Aside: my next PR will build on this to add support for `{ [topicname]: [r/w/rw] }` maps. I'd also like to deprecate a few of the config option names and suggest some new ones if that's ok with you.)

[mongo] Support embedded topic lists

---

README.md
be-mongo.c

Builds on https://github.com/jpmens/mosquitto-auth-plug/pull/210. Add support for r/w/rw topics with a mongo backend via sub-document 'maps' of the form `{ [topic: string]: "r"|"w"|"rw" }`.
(Let me know if a different API would be preferred - I did consider `"readTopics": ["t1","t2"], "writeTopics": ["t3","t4"]` etc which is marginally more space-efficient but IMO isn't as neat, and introduces more config options.)

[mongo] Support ACL maps

---

README.md
be-mongo.c

MongoDB [connection strings](https://docs.mongodb.com/manual/reference/connection-string/) support a huge number of options, more than we could hope to support via individual parameters in `mosquitto.conf`. In particular, replica sets can only be specified via connection strings.
This introduces support for configuring the connection string (uri) directly. It also fixes the previous unchecked 128 char limit on connection strings.
Requires `mongo-c-driver` >= `1.4.0` for option setters.

[mongo] Support mongo URIs

---

README.md
be-mongo.c
hash.c
hash.h

Builds on https://github.com/jpmens/mosquitto-auth-plug/pull/214.
- Deprecate the DIY connection options (because any choice of which to support is more or less arbitrary) in favour of the URI string (because that supports everything). 
- Add a configuration option for the name of the `username` property.
- Rename other configuration options for consistency and meaning.
- Fix a minor memory leak (conf never freed) and some odd behaviour whereby free would be called on string literals (default config values) and on anything returned from `p_stab`.
- `p_stab` should accept a `const char*` key.

[mongo] Rename/deprecate/add config options

---

README.md

The redis implementation does a simple 'GET username-topic', and makes no attempt to match topics against wildcards. Just documenting this for now.

Document no wildcards on Redis

---

be-postgres.c

Send param as text instead of binary.

---

be-mongo.c

A nasty copy/paste slip in my previous commit broke the mongo backend - not sure how that slipped through, apologies. This should fix it but I won't be at a machine to test it until Thursday.

[mongo] Fix typo/bug in username config

---

Makefile
be-mongo.c

Since we already require mongo-c-driver >= 1.4.0 we can remove replace these functions deprecated in 1.3.0 and re-enable`no-deprecated-declarations`.

[mongo] Replace deprecated calls

---

Makefile
config.mk.in

Use of additional config variable to guard against default CFLAGS settings from make.
Change handling of LDFLAGS to work like CFLAGS.
This will allow to configure a compilation with debug flag, for example.

Allow config to add flags to CFLAGS via CFG_CFLAGS.

---

Makefile
auth-plug.c
be-files.c
be-files.h

Reimplementation of mosquitto password and ACL file behavior.
Allows the auth-plug use files and data dases.
passwords are in auth-plug PBKDEF2 format.
Fixes #216
From mosquitto config:
Control access to topics on the broker using an access control list
file. If this parameter is defined then only the topics listed will
have access.
If the first character of a line of the ACL file is a # it is treated as a
comment.
Topic access is added with lines of the format:
topic [read|write] <topic>
The access type is controlled using "read" or "write". This parameter
is optional - if not given then the access is read/write.
<topic> can contain the + or # wildcards as in subscriptions.
The first set of topics are applied to anonymous clients, assuming
allow_anonymous is true. User specific topic …

Password and ACL files based backend.

---

auth-plug.c
be-cdb.c
be-redis.c

Fix a double free on mosquitto shutdown:
```
1495109810: mosquitto version 1.4.10 terminating                                                                     
1495109810: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.                                            
*** Error in `/usr/sbin/mosquitto': double free or corruption (fasttop): 0x0000000002216f50 ***                       
======= Backtrace: =========                                                                                          
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f8f6b46e7e5]                                                             
/lib/x86_64-linux-gnu/libc.so.6(+0x7fe0a)[0x7f8f6b476e0a] …
```

Fix double-free

---

be-postgres.c

Latest commit on master (1ac1ce8) broke compilation of be-postgresql:
```
be-postgres.c: In function 'be_pg_superuser':
be-postgres.c:189:3: error: unknown type name '$1'
$1 instead of % s
^
be-postgres.c:189:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'of'
$1 instead of % s
^
be-postgres.c:194:60: error: 'values' undeclared (first use in this function)
res = PQexecParams(conf->conn, conf->superquery, 1, NULL, values, lengths, binary, 0);
^
be-postgres.c:194:60: note: each undeclared identifier is reported only once for each function it appears in
be-postgres.c: In function 'be_pg_aclcheck':
be-postgres.c:249:3: error: expected expression before '^' token
^32 + 1
^
be-postgres.c:251:11: error: 'accbuffer' undeclared (first use in this function)
snprintf(accbuffer, …
```

Fix build of be-postgres

---

cache.c

libressl is forked from openssl but it implements an earlier version of openssl
with a greater version number. In cache.c code tries to use EVP_MD_CTX_new
instead of EVP_MD_CTX_create, leading to a build error.
This helps to build mosquitto-auth-plug inside Docker using Alpine, which builds
postgresql with libressl.
It is also probably not future proof since, if libressl implements similar functions, LIBRESSL_VERSION_NUMBER needs to be compared against that instead of
just being defined - nothing we can do anything about now.

Make cache.c compatible with libressl

---

Makefile

So we can link on macOS against libcrypto in brew using this in config.mk:
```bash
MOSQUITTO_SRC = /usr/local/Cellar/mosquitto/1.4.12
OPENSSLDIR = /usr
#	CFG_LDFLAGS = -undefined dynamic_lookup
CFG_LDFLAGS = -undefined dynamic_lookup  -L/usr/local/Cellar/openssl/1.0.2l/lib
CFG_CFLAGS = -I/usr/local/Cellar/openssl/1.0.2l/include -I/usr/local/Cellar/mosquitto/1.4.12/include

Also use LDFLAGS when compiling and linking np 

---

contrib/C#/README.md

The code won't work if you don't compile with the -DRAW_SALT flag.  I added a readme.md that indicates what they need to do.  Sorry it wasn't originally included

Add readme instructing to use -DRAWSALT program will not work otherwise

---

be-http.c

Prevent `basic_auth` from being uninitialized.

Fix memory fault

---

Makefile

This commit fixes backward compatibility of the config.mk file (#303).
The plugin now defaults to the standard $PBKDF2$ convention instead of the Django _pbkdf2_ convention if the SUPPORT_DJANGO_HASHERS option is left undefined.

use standard PBKDF2 if Django option is undefined

---

README.md
log.h

Following #299, logging use mosquitto_log_printf. But Mosquitto don't use the value 1 for debug priority (it use 0x10).
This use the correct value by using Mosquitto include file.
Also update README to state that log_quiet is no longer used with Mosquitto >= 1.4

Fix logging with Mosquitto >= 1.4

---

auth-plug.c
backends.h
be-cdb.c
be-cdb.h
be-files.c
be-files.h
be-http.c
be-http.h
be-jwt.c
be-jwt.h
be-ldap.c
be-ldap.h
be-mongo.c
be-mongo.h
be-mysql.c
be-mysql.h
be-postgres.c
be-postgres.h
be-psk.c
be-redis.c
be-redis.h
be-sqlite.c
be-sqlite.h

This PR no longer cache error that occur during authentication.
Before this PR, if an authentication failed (e.g. with HTTP backend, server is down or return 500), the plugin returned MOSQ_ERR_AUTH and the result was cached for the duration of auth_cacheseconds.
After this PR, if an authentication failed, the plugin returns MOSQ_ERR_UNKNOWN (which also result in connection refused for the client) and will NOT cache this result.
This will clone behavior of ACL check, that also does not cache backend error.
To support this feature, the getuser method of backends need a way to inform of error condition. To achieve this I've permuted the output parameter authenticated and the return value (password hash for PKDF2), which allow to have a return code.
This return code have 4 values:
* Allow: …

Don't cache authentication failure

---

README.md
auth-plug.c
cache.c
cache.h
userdata.h

Added a cache TTL jitter. As explained in README this should reduce lookups storm on backend when lots of client reconnect as the same time. This could easily occur when the Mosquitto server is restarted: all clients get disconnected and will all reconnect quickly. This will cause a storm of lookups (can't really avoid this one, cache is in memory and process was restarted). But without any jitter, every acl_cacheseconds a new lookup storm will happen.
By adding a random jitter, this storm will be spread over a larger time avoiding a high load spike.
To keep compatibility, default value is 0 (disabled). Also updated the README to:
* Move cache options to global section (instead of MySQL one, cache is not MySQL specific).
* Added a short explanation of cache and jitter and why it's useful.

Add cache jitter

---

be-jwt.c

fix for jwt token_header overflow by one. 
22 is the length of the ""Authorization: Bearer " char array, but sprintf adds null at the end of token_header and that crashed the plugin every time with 
2017-09-12T08:55:50.633878547Z mosquitto: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
I used the this jwt to replicate:
key eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyNCIsImF1dGgiOltdLCJ0b3BpY3MiOlsiMSIsIjIiLCIzIiwiNCIsIjI2IiwiMzIiXSwiZXhwIjoxNTAyMjg1NzM5fQ.RhpfXZHWf4p3msFgHAmdJPjgrxogPSufOcT8_lLeE5bI1Yme7GkFk7WFt4V-pAEwm3llzzloYgnycSh_y5JYVg
It fails for me every time.

fix for jwt malloc.c:2394: sysmalloc: Assertion

---

be-postgres.c

This fixes the following:
```
cc  -I/mqtt/mosquitto/src/ -I/mqtt/mosquitto/lib/ -fPIC -Wall -Werror  -DBE_CDB -DBE_POSTGRES -DBE_HTTP -DBE_JWT -DBE_FILES  -Icontrib/tinycdb-0.78// -I`pg_config --includedir` -I/src -DDEBUG=1 -I/mqtt/openssl/include   -c -o be-postgres.o be-postgres.c
be-postgres.c: In function 'addKeyValue':
be-postgres.c:392:25: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
while (*(keywords + n) != '\0')
^~
be-postgres.c:392:9: note: did you mean to dereference the pointer?
while (*(keywords + n) != '\0')
^
be-postgres.c:404:19: error: comparison between pointer and zero character constant [-Werror=pointer-compare]
if ((keywords[n] != '\0') || (values[n] != '\0')){
^~
be-postgres.c:404:7: note: did you mean to dereference the …
```

Fixed warnings for this to build cleanly with gcc 7.3.0.

---

backends.c
backends.h
be-mongo.c

Add support for expansion of `%c` and `%u` as clientid and username
respectively (just like the mysql backend).
Example: say the ACL for user 'example-user' contains the topic `users/%u/demo`.
This user is then granted access to the expanded topic `users/example-user/demo`.
As this feature already exists for the mysql backend, I modeled this patch after the mysql backend code.
Because `permitted_topic` is of type `const char *` in the mongo backend, I have modified function `t_expand` to expect a `const char *in`.

Mongo backend: support expansion of %c and %u

---

contrib/nodejs/README.md
contrib/nodejs/np.js
contrib/nodejs/package.json

The library "prompt" for the simple test script requires another lib with a security bug. The automatic snyk test tool flags this as low severity. As both libs (prompt and utile) are not updated for a long time Stefan Seide changed the np.js script to use another more actively maintained library without security warning.
✗ Low severity vulnerability found in utile
Description: Uninitialized Memory Exposure
Info: https://snyk.io/vuln/npm:utile:20180614
Introduced through: mosquitto-pbkdf2@0.2.1
From: mosquitto-pbkdf2@0.2.1 > prompt@1.0.0 > utile@0.3.0

Merged PR https://github.com/manolodd/mosquitto-pbkdf2/pull/2 
